# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e014db1ea9c742eb370a0851ee554747a11e54332c9abb8c7824098f7aa40817157b7255e59390e21eb685c0c259148ffee1b28f5a2c45a9009041de20c698a

test:
  secret_key_base: 34238a2ce904a3b8e8340225ba482ff2ebcf330ba4b53ce6faaac1a93cad2732c53118ee55a70466413a9d9214ee5b54810508b85bc89e10e2c35f5df1778e67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
